### ISSUE TITLE
wield3d mod breaks near node effects

### ISSUE THREAD

**Issue by tacotexmex** [pyrollo/late#10]
I finally hunted down a bug where near node effects don't work when [wield3d](https://github.com/stujones11/wield3d) mod is loaded. Seemingly, the `wield3d:wield_entity` object blocks the effect from impacting the player.

When disabling wield3d, it leaves this `wield3d:wield_entity` behind and so when removing that entity (punching it), the effect works again.

![screenshot_20181122_120936](https://user-images.githubusercontent.com/25328789/48899412-d3eaaf00-ee4f-11e8-98da-b131080ccd5e.png)

**Comment by pyrollo** [comment]
Interersting ! Do you have anything in logs ? 

I guess the ABM loop goes wrong somewhere with this entity.

**Comment by tacotexmex** [comment]
> Interersting ! Do you have anything in logs ?

Not that I’ve seen, but you may replicate it easy enough. :)

**Comment by pyrollo** [comment]
Nice finding. Actually the problem with object attachment. Problem is the same with boats, you can approach on boat without triggering the effect. 
The entity to which the player is attached hides the player from the ABM.

**Comment by pyrollo** [comment]
Fixed in aa117680aeb29fb525f3e5d114fed931a98d0dba
