### ISSUE TITLE
Player effect persistance

### ISSUE THREAD

**Issue by tacotexmex** [pyrollo/late#3]
> Persistance of effects on mobs (now only player effects persist)

1. Drink the poison vessel and exit the world upon seeing the effect has started
2. Re-enter the world
3. Effect is now gone instead of running the remainder of its time

(Death doesn't stop it however, even with `stop_on_death = true`).

**Comment by pyrollo** [comment]
That was because code for player effects persistence was commented. 
This is fixed now. As is the "stop on death" bug (silly typo).

Commit 9f330c57f562bc23cef2ca93f38c300b7d89e0c9
